name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: scavinator_test
        volumes:
          - ./script/pg_ci_setup.sh:/docker-entrypoint-initdb.d/01_schema.sh:ro
          - ./script/pg_test_setup.sh:/docker-entrypoint-initdb.d/02_test_setup.sh:ro
        ports:
          - 5433:5432
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test
